# Generated by Django 4.1.7 on 2023-02-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0010_dweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
